In [3]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [24]:
#Method 1: from scratch using arrays(not commonly used)
df_1 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                    columns = ['a', 'b', 'c'])
df_1

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [28]:
#method 2: from scratch using dictionaries
data_dict = {'fruits': ['apple', 'banana', 'mango', 'strawberry'],
            'vegetables': ['carrot', 'broccoli', 'spinach', 'artichoke'],
            'nuts': ['almonds', 'walnut', 'pistachios', 'cashews']}

df_2 = pd.DataFrame(data=data_dict)
df_2

       fruits vegetables        nuts
0       apple     carrot     almonds
1      banana   broccoli      walnut
2       mango    spinach  pistachios
3  strawberry  artichoke     cashews

In [ ]:
#Method 3: From an existing source or file
df_titanic = pd.read_csv('titanic_file.csv')
#make sure this is downloaded and within the right folder
df_titanic

In [34]:
#SLICING
#df.loc[]: label indexing
#df.iloc[]: integer indexing

In [42]:
#generating data
anes96 = sm.datasets.anes96
print(anes96.NOTE)
#saving as dataframe
dataset_anes96 = anes96.load_pandas()
elections_df = dataset_anes96.data
elections_df

::

    Number of observations - 944
    Number of variables - 10

    Variables name definitions::

            popul - Census place population in 1000s
            TVnews - Number of times per week that respondent watches TV news.
            PID - Party identification of respondent.
                0 - Strong Democrat
                1 - Weak Democrat
                2 - Independent-Democrat
                3 - Independent-Indpendent
                4 - Independent-Republican
                5 - Weak Republican
                6 - Strong Republican
            age : Age of respondent.
            educ - Education level of respondent
                1 - 1-8 grades
                2 - Some high school
                3 - High school graduate
                4 - Some college
                5 - College degree
                6 - Master's degree
                7 - PhD
            income - Income of household
                1  - None or less than $2,999
                2  - $3,000-$4,999
                3  - $5,000-$6,999
                4  - $7,000-$8,999
                5  - $9,000-$9,999
                6  - $10,000-$10,999
                7  - $11,000-$11,999
                8  - $12,000-$12,999
                9  - $13,000-$13,999
                10 - $14,000-$14.999
                11 - $15,000-$16,999
                12 - $17,000-$19,999
                13 - $20,000-$21,999
                14 - $22,000-$24,999
                15 - $25,000-$29,999
                16 - $30,000-$34,999
                17 - $35,000-$39,999
                18 - $40,000-$44,999
                19 - $45,000-$49,999
                20 - $50,000-$59,999
                21 - $60,000-$74,999
                22 - $75,000-89,999
                23 - $90,000-$104,999
                24 - $105,000 and over
            vote - Expected vote
                0 - Clinton
                1 - Dole
            The following 3 variables all take the values:
                1 - Extremely liberal
                2 - Liberal
                3 - Slightly liberal
                4 - Moderate
                5 - Slightly conservative
                6 - Conservative
                7 - Extremely Conservative
            selfLR - Respondent's self-reported political leanings from "Left"
                to "Right".
            ClinLR - Respondents impression of Bill Clinton's political
                leanings from "Left" to "Right".
            DoleLR  - Respondents impression of Bob Dole's political leanings
                from "Left" to "Right".
            logpopul - log(popul + .1)

,popul,TVnews,selfLR,ClinLR,DoleLR,PID,age,educ,income,vote,logpopul
0,0.0,7.0,7.0,1.0,6.0,6.0,36.0,3.0,1.0,1.0,-2.302585
1,190.0,1.0,3.0,3.0,5.0,1.0,20.0,4.0,1.0,0.0,5.247550
2,31.0,7.0,2.0,2.0,6.0,1.0,24.0,6.0,1.0,0.0,3.437208
3,83.0,4.0,3.0,4.0,5.0,1.0,28.0,6.0,1.0,0.0,4.420045
4,640.0,7.0,5.0,6.0,4.0,0.0,68.0,6.0,1.0,0.0,6.461624
...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,7.0,7.0,1.0,6.0,4.0,73.0,6.0,24.0,1.0,-2.302585
940,0.0,7.0,5.0,2.0,6.0,6.0,50.0,6.0,24.0,1.0,-2.302585
941,0.0,3.0,6.0,2.0,7.0,5.0,43.0,6.0,24.0,1.0,-2.302585
942,0.0,6.0,6.0,2.0,5.0,6.0,46.0,7.0,24.0,1.0,-2.302585
943,18.0,7.0,4.0,2.0,6.0,3.0,61.0,7.0,24.0,1.0,2.895912

In [44]:
elections_df.loc[4, 'TVnews']

7.0

In [50]:
new_df = elections_df.iloc[4:8, 3:6]

In [54]:
elections_df['age'] #only works with column names

0      36.0
1      20.0
2      24.0
3      28.0
4      68.0
       ...
939    73.0
940    50.0
941    43.0
942    46.0
943    61.0
Name: age, Length: 944, dtype: float64